[package]
name = "libimagcounter"
version = "0.1.0"
authors = ["Matthias Beyer <mail@beyermatthias.de>"]

[dependencies]
toml = "0.1.25"
semver = "0.2"

[dependencies.libimagstore]
path = "../libimagstore"

